theme: jekyll-theme-slate
title: Владимир Низов. Книги и публикации
author: Владимир Низов
description: Официальный сайт и портфолио Владимира Низова. Здесь вы найдете публикации по программированию на Java, структурам данных, алгоритмам и другим техническим темам.
