theme: jekyll-theme-slate
title: Владимир Низов. Книги и публикации
author: Владимир Низов
description: Здесь вы найдете публикации по программированию на Java, структурам данных, алгоритмам и другим техническим темам.
